apiVersion: v1
kind: ConfigMap
metadata:
  name: docuseal-config
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/docuseal"
  RAILS_LOG_TO_STDOUT: "true"
  RAILS_LOG_LEVEL: "debug"
