apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: docuseal
spec:
  type: ClusterIP
  selector:
    app: docuseal
  ports:
    - port: 9128
      targetPort: 3000
